# Alert Configuration
# Manages notifications via Slack, Telegram, and Email

# Minimum alert level to send (info, warning, error, critical)
min_level: info

# Alert types to enable
enabled_types:
  - fill
  - order_reject
  - risk_violation
  - system_error
  - daily_summary

# Slack configuration
slack:
  enabled: false
  bot_token: ${SLACK_BOT_TOKEN}
  webhook_url: ${SLACK_WEBHOOK_URL}
  default_channel: "#trading-alerts"
  username: "Mech-Exo Bot"

# Email configuration
email:
  enabled: false
  smtp_server: smtp.gmail.com
  smtp_port: 587
  sender_email: ${EMAIL_SENDER}
  sender_password: ${EMAIL_PASSWORD}
  recipient_emails:
    - ${EMAIL_RECIPIENT}

# Telegram configuration
telegram:
  enabled: true
  bot_token: ${TELEGRAM_BOT_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}
  username: "Mech-Exo Bot"

# Notes:
# - Set environment variables for sensitive tokens
# - For Telegram: Create bot with @BotFather, get chat_id from @userinfobot
# - Use TELEGRAM_DRY_RUN=true for testing without actual sends
EOF < /dev/null