# Capital Limits Configuration
# Manages maximum capital allocation per account for production trading
# Phase P11 Week 3: Capital expansion x5 with multi-account support

capital_limits:
  # Production accounts with maximum allocation limits
  accounts:
    # Primary production account - merged from canary (Phase P11 Week 3)
    U1234567:  # Primary USD account
      max_capital: 250000  # 50% of total 500k capital
      currency: USD
      enabled: true
      added_date: "2025-01-15"
      category: "production"
      allocation_pct: 50.0
      notes: "Primary USD trading account - merged from canary system"
      region: "north_america"
      type: "ib_individual"
      
    # Secondary production account - new for expansion
    U1234568:  # Secondary CAD account  
      max_capital: 250000  # 50% of total 500k capital (USD equivalent)
      currency: CAD
      currency_limit_cad: 337500  # CAD equivalent at 1.35 rate
      enabled: true
      added_date: "2025-06-13"
      category: "production"
      allocation_pct: 50.0
      notes: "Secondary CAD trading account - Phase P11 Week 3 expansion"
      region: "canada"
      type: "ib_individual"
      
    DU1003STAGING:  # Staging/test account (unchanged)
      max_capital: 25000   # Small staging allocation
      currency: USD
      enabled: true
      added_date: "2025-06-13"
      category: "staging"
      allocation_pct: 5.0
      notes: "Staging environment testing"
  
  # Global settings
  global:
    # Overall maximum across all accounts (Phase P11 Week 3: 5x expansion)
    total_max_capital: 500000  # Increased from 100k to 500k (5x expansion)
    
    # Multi-account settings
    max_accounts: 2  # Current: 2 production accounts
    account_count: 2  # U1234567 (USD) + U1234568 (CAD)
    
    # Default currency for new accounts
    default_currency: USD
    
    # Safety margin (percentage of buying power to reserve)
    safety_margin_pct: 10
    
    # Alert thresholds (production-ready)
    alerts:
      warning_threshold_pct: 75   # Alert when usage > 75%
      critical_threshold_pct: 90  # Critical alert when usage > 90%
      
    # Phase P11 Week 3 production thresholds
    production_monitoring:
      max_daily_drawdown_pct: 2.0    # Max 2% daily loss across all accounts
      max_position_concentration_pct: 5.0   # Max 5% in single position (tightened)
      max_sector_exposure_pct: 25.0  # Max 25% in single sector (tightened)
      max_single_account_pct: 60.0   # Max 60% of capital in single account
      
    # Cross-account risk management
    multi_account_limits:
      max_correlation_threshold: 0.7   # Max correlation between account positions
      enable_cross_account_netting: true
      currency_hedge_threshold_pct: 10.0  # Hedge FX exposure >10%
      
    # Monitoring frequency
    check_frequency_minutes: 10  # Check every 10 minutes during market hours
    after_hours_frequency_minutes: 30  # Check every 30 minutes after hours
    
# Capital utilization tracking
utilization:
  last_check: null
  accounts: {}
  # Will be populated with:
  # DU12345678:
  #   buying_power: 85000
  #   used_capital: 65000
  #   utilization_pct: 76.47
  #   last_updated: "2025-06-15T14:30:00Z"
  #   status: "ok"  # ok, warning, critical

# Historical tracking
history:
  # Track capital limit changes
  changes:
    - timestamp: "2025-06-13T21:55:00Z"
      action: "merge_canary_accounts"
      account: "U1234567"
      old_limit: 100000
      new_limit: 250000
      user: "phase-p11w3-deployment"
      notes: "Merged canary system into production account"
      
    - timestamp: "2025-06-13T21:55:00Z"
      action: "add_account"
      account: "U1234568"
      old_limit: null
      new_limit: 250000
      currency: "CAD"
      user: "phase-p11w3-deployment"
      notes: "Added secondary CAD account for capital expansion"
      
    - timestamp: "2025-06-13T21:55:00Z"
      action: "update_global_limits"
      old_total: 100000
      new_total: 500000
      user: "phase-p11w3-deployment"
      notes: "Capital expansion x5: 100k -> 500k total"