# Capital Limits Configuration
# Manages maximum capital allocation per account for production trading
# Phase P11 Week 2: Expanded from 30% to 50% canary allocation

capital_limits:
  # Production accounts with maximum allocation limits
  accounts:
    # Canary accounts - Phase P11 Week 2 expansion to 50%
    DU1001CANARY:  # Primary canary account
      max_capital: 250000  # Increased from 150k to 250k (35% allocation)
      currency: USD
      enabled: true
      added_date: "2025-06-13"
      category: "canary"
      allocation_pct: 35.0
      notes: "Primary canary - Phase P11 Week 2 expansion"
      
    DU1002CANARY:  # Secondary canary account  
      max_capital: 150000  # Increased from 100k to 150k (15% allocation)
      currency: USD
      enabled: true
      added_date: "2025-06-13"
      category: "canary"
      allocation_pct: 15.0
      notes: "Secondary canary - diversification"
      
    DU1003STAGING:  # Staging/test account
      max_capital: 25000   # Small staging allocation
      currency: USD
      enabled: true
      added_date: "2025-06-13"
      category: "staging"
      allocation_pct: 5.0
      notes: "Staging environment testing"
  
  # Global settings
  global:
    # Overall maximum across all accounts (increased for canary expansion)
    total_max_capital: 1000000  # Increased from 500k to 1M
    
    # Default currency for new accounts
    default_currency: USD
    
    # Safety margin (percentage of buying power to reserve)
    safety_margin_pct: 10
    
    # Alert thresholds (tightened for production)
    alerts:
      warning_threshold_pct: 75   # Alert when usage > 75% (tightened)
      critical_threshold_pct: 90  # Critical alert when usage > 90% (tightened)
      
    # Phase P11 specific thresholds
    canary_monitoring:
      max_daily_drawdown_pct: 2.0    # Max 2% daily loss for canary accounts
      max_position_concentration_pct: 15.0  # Max 15% in single position
      max_sector_exposure_pct: 30.0  # Max 30% in single sector
      
    # Monitoring frequency (increased for production)
    check_frequency_minutes: 15  # Check every 15 minutes during market hours
    after_hours_frequency_minutes: 60  # Check hourly after hours
    
# Capital utilization tracking
utilization:
  last_check: null
  accounts: {}
  # Will be populated with:
  # DU12345678:
  #   buying_power: 85000
  #   used_capital: 65000
  #   utilization_pct: 76.47
  #   last_updated: "2025-06-15T14:30:00Z"
  #   status: "ok"  # ok, warning, critical

# Historical tracking
history:
  # Track capital limit changes
  changes: []
  # Will store:
  # - timestamp: "2025-06-15T10:00:00Z"
  #   action: "add_account"
  #   account: "DU12345678"
  #   old_limit: null
  #   new_limit: 100000
  #   user: "admin"