# Risk Management Configuration

# Position Sizing Limits
position_sizing:
  max_single_trade_risk: 0.02      # 2% of NAV per trade
  max_sector_exposure: 0.20        # 20% of NAV per sector
  max_single_position: 0.10        # 10% of NAV per position
  min_position_size: 100           # Minimum USD position size

# Portfolio Level Limits
portfolio:
  max_gross_exposure: 1.5          # 150% of NAV (1.5x leverage)
  max_net_exposure: 1.0            # 100% of NAV net long/short
  max_drawdown: 0.10               # 10% maximum drawdown
  correlation_limit: 0.7           # Max correlation between positions

# Options Specific
options:
  max_theta_burn: -0.005           # -0.5% NAV per day from theta decay
  max_vega_exposure: 0.05          # 5% NAV volatility exposure
  max_gamma_exposure: 0.03         # 3% NAV gamma exposure
  max_days_to_expiry: 45           # Don't hold options < 45 DTE

# Stop Loss Configuration
stops:
  trailing_stop_pct: 0.25          # 25% trailing stop from peak
  hard_stop_pct: 0.15              # 15% hard stop loss
  profit_target_pct: 0.30          # 30% profit target
  time_stop_days: 60               # Exit after 60 days regardless

# Cost Controls
costs:
  commission_cap_pct: 0.30         # Fees <= 30% of gross P/L
  max_slippage_bps: 50             # Max 50 bps slippage per trade
  min_spread_quality: 0.02         # Min bid-ask spread as % of mid

# Operational Limits
operational:
  max_trades_per_day: 20           # Maximum number of trades per day
  max_orders_per_minute: 5         # Rate limiting
  market_hours_only: true          # Only trade during market hours
  pre_market_allowed: false        # Allow pre-market trading
  after_hours_allowed: false       # Allow after-hours trading

# Volatility Controls
volatility:
  max_portfolio_vol: 0.20          # 20% annualized portfolio volatility
  vol_lookback_days: 30            # Days to calculate volatility
  vol_scaling_factor: 1.0          # Volatility scaling multiplier

# Margin Requirements
margin:
  maintenance_margin_buffer: 0.25  # 25% buffer above maintenance
  initial_margin_buffer: 0.15      # 15% buffer above initial
  max_margin_usage: 0.80           # 80% of available margin